### ISSUE TITLE
Suite with NSSL MP will not compile on its own due to missing module_mp_radar

### ISSUE THREAD

**Issue by LarissaReames** [ufs-community/ccpp-physics#243]
# Description

When a suite that uses NSSL MP is compiled alone, it fails when compiling module_mp_thompson due to a missing module_mp_radar.  Its attempting to compile module_mp_thompson as it's a dependency of GFS_rrtmg_pre, but it appears that make is not also detecting the module_mp_radar is a dependency of module_mp_thompson. When I add module_mp_radar.F90 to the dependencies in GFS_rrtmg_pre.meta, the suite compiles successfully.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Attempt to compile ufs-weather-model with suite_FV3_RRFS_v1nssl.xml and no other CCPP suite
2. Build files when attempting to compile module_mp_thompson.F90

## Additional Context

* Machine : Hera
* Compiler : Intel
* Suite Definition File or Scheme : suite_FV3_RRFS_v1nssl.xml

## Output

Initial error, followed by lots of "this name does not have a type" errors:
`/scratch1/BMC/gsd-fv3/Larissa.Reames/ufs-weather-model-develop/FV3/ccpp/physics/physics/MP/Thompson/module_mp_thompson.F90(63): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MODULE_MP_RADAR]
   use module_mp_radar`
